version: "3.8"
services:
  bookmark-frontend:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
      - /app/node_modules
    env_file:
      - .env
    container_name: bookmark_frontend
    command: npm start
