version: "3.8"  # Specify the Docker Compose version

services:
  postgres:
    image: postgres:latest  # Use the latest PostgreSQL image
    container_name: postgres_container  # Optional: name the container
    restart: always  # Ensure the container restarts on failure
    ports:
      - "5434:5432"  # Map the container's port 5432 to the host's port 5432
    environment:
      POSTGRES_USER: user  # Set the username for the database
      POSTGRES_PASSWORD: 1234  # Set the password for the database
      POSTGRES_DB: bookmarks  # Create a default database
    volumes:
      - postgres_bookmark_data:/var/lib/postgresql/data  # Persist data across restarts

volumes:
  postgres_bookmark_data:  # Define a named volume for persistent data storage